default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tweety_development
test:
  <<: *default
  database: tweety_test
production:
  <<: *default
  database: tweety_production
  username: tweety
  password: <%= ENV['TWEETY_DATABASE_PASSWORD'] %>
